config/routes.rb
Rails.application.routes.draw do
  resources :britts
  resources :users
  root 'users#index'

end

app/models/britt.rb
class Britt < ActiveRecord::Base
  belongs_to :user
  validates :content, length: { maximum: 200 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :britts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  def hello
    render text: "Hola, mundo!"
  end
  
  def goodbye
    render text: "Adios, mundo!"
  end
end

app/controllers/britts_controller.rb
class BrittsController < ApplicationController
  before_action :set_britt, only: [:show, :edit, :update, :destroy]

  # GET /britts
  # GET /britts.json
  def index
    @britts = Britt.all
  end

  # GET /britts/1
  # GET /britts/1.json
  def show
  end

  # GET /britts/new
  def new
    @britt = Britt.new
  end

  # GET /britts/1/edit
  def edit
  end

  # POST /britts
  # POST /britts.json
  def create
    @britt = Britt.new(britt_params)

    respond_to do |format|
      if @britt.save
        format.html { redirect_to @britt, notice: 'Britt was successfully created.' }
        format.json { render :show, status: :created, location: @britt }
      else
        format.html { render :new }
        format.json { render json: @britt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /britts/1
  # PATCH/PUT /britts/1.json
  def update
    respond_to do |format|
      if @britt.update(britt_params)
        format.html { redirect_to @britt, notice: 'Britt was successfully updated.' }
        format.json { render :show, status: :ok, location: @britt }
      else
        format.html { render :edit }
        format.json { render json: @britt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /britts/1
  # DELETE /britts/1.json
  def destroy
    @britt.destroy
    respond_to do |format|
      format.html { redirect_to britts_url, notice: 'Britt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_britt
      @britt = Britt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def britt_params
      params.require(:britt).permit(:content, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :username, :description, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/britts_helper.rb
module BrittsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/britts/_form.html.erb
<%= form_for(@britt) do |f| %>
  <% if @britt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@britt.errors.count, "error") %> prohibited this britt from being saved:</h2>

      <ul>
      <% @britt.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/britts/edit.html.erb
<h1>Editing Britt</h1>

<%= render 'form' %>

<%= link_to 'Show', @britt %> |
<%= link_to 'Back', britts_path %>

app/views/britts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Britts</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @britts.each do |britt| %>
      <tr>
        <td><%= britt.content %></td>
        <td><%= britt.user_id %></td>
        <td><%= link_to 'Show', britt %></td>
        <td><%= link_to 'Edit', edit_britt_path(britt) %></td>
        <td><%= link_to 'Destroy', britt, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Britt', new_britt_path %>

app/views/britts/new.html.erb
<h1>New Britt</h1>

<%= render 'form' %>

<%= link_to 'Back', britts_path %>

app/views/britts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @britt.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @britt.user_id %>
</p>

<%= link_to 'Edit', edit_britt_path(@britt) %> |
<%= link_to 'Back', britts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Brittle</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Description</th>
      <th>Location</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.username %></td>
        <td><%= user.description %></td>
        <td><%= user.location %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>